import { Component, ViewChild, ElementRef } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';
import { Storage } from '@ionic/storage';
import { StatisticsServiceProvider } from '../../providers/statistics-service/statistics-service';
import { LoginPage } from '../login/login';
import { LoginServiceProvider } from '../../providers/login-service/login-service';
import { Statistics } from 'domain/statistics';
import { Chart } from 'chart.js'



@IonicPage()
@Component({
  selector: 'page-statistics',
  templateUrl: 'statistics.html',
})

/**
 * The page responsible for managing the StatisticsPage.
 * @class StatisticsPage
 * @module AppModule
 * @submodule Pages
 */
export class StatisticsPage {

  /**
   * Holds a copy of the statistics canvas element
   * @type {ElementRef}
   * @memberof StatisticsPage
   * @property barCanvas
   */
  @ViewChild('barCanvas') barCanvas: ElementRef;

  /**
   * Holds a copy of the statistics object
   * @type {Statistics}
   * @memberof StatisticsPage
   * @property stats
   */
  stats: Statistics;

  /**
   * A numerical value which indicates the percentage of total progress made by the user.
   * @type {number}
   * @memberof StatisticsPage
   * @property progress
   */
  progress: number;

  /**
   * Used to hold the bar chart generated by Chart.js.
   * @type {*}
   * @memberof StatisticsPage
   * @property barChart
   */
  barChart: any;

  /**
   * A boolean indicating whether the loading bar has finished loading.
   * @type {boolean}
   * @memberof StatisticsPage
   * @property loadedBar
   */
  loadedBar: boolean;

  /**
   * A string which keeps track of when the page should be refreshed.
   * @type {string}
   * @memberof StatisticsPage
   * @property loadRefresh
   */
  loadRefresh: string = "Load";

  /**
   * Creates an instance of StatisticsPage.
   * @param {NavController} navCtrl base class for navigation controller components like Nav and Tab.
   * @param {NavParams} navParams class for navigation controller parameters in Ionic.
   * @param {LoginServiceProvider} loginProvider A dependency injected instance of the login Service.
   * @param {StatisticsServiceProvider} statisticsProvider A dependency injected instance of the statistics Service.
   * @param {Storage} storage Uses a variety of storage engines underneath, picking the best one available depending on the platform.
   * @memberof StatisticsPage
   * @method constructor
   */
  constructor(public navCtrl: NavController, public navParams: NavParams,
    private loginProvider: LoginServiceProvider, private statisticsProvider: StatisticsServiceProvider,
    private storage: Storage) {
  }

  /**
   * Lifecycle hook which is fired when entering a page, before it becomes the active one.
   * @memberof StatisticsPage
   * @method ionViewDidEnter
   */
  ionViewDidEnter(){
    this.onStartReload();
  }

  /**
   * Updates the progress bar on the statistics page.
   * @memberof StatisticsPage
   * @method updateProgressBar
   */
  updateProgressBar(){
    let completionDate = this.stats.getApproximateEndDate() as any;
    let startDate = this.stats.getEarlierstDate() as any;
    let currentDate = new Date() as any;
    this.progress = Math.round(
                      (Math.abs(currentDate - startDate)/ Math.abs(completionDate - startDate))*100
                    )
  }

  /**
   * Updates the bar graph on the statistics page.
   * @memberof StatisticsPage
   * @method updateBarGraph
   */
  updateBarGraph(){
    this.loadedBar = true;
    let data = Array<number>();
    this.loadRefresh = "Refresh";
    data.push(this.stats.getAverageSuccessOfExercies('Heel Raises'));
    data.push(this.stats.getAverageSuccessOfExercies('Towel Stretch'));
    data.push(this.stats.getAverageSuccessOfExercies('Step Ups'));
    data.push(this.stats.getAverageSuccessOfExercies('Standing Calf Stretch'));
    this.barChart = new Chart(this.barCanvas.nativeElement, {
      type: 'bar',
      data: {
          labels: ["HR", "TS", "SU", "SCS"],
          datasets: [{
              label: 'Success Rate %',
              data: data,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)'
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          },
          maintainAspectRatio: false,
          responsive: true
      }

    });
  }

  /**
   * Validates the users session and updates the statistics page with the relevant data.
   * @memberof StatisticsPage
   * @method onStartReload
   */
  onStartReload(){
    this.storage.get('sessionId').then(sessionId =>{
      if (!sessionId) {
        this.navCtrl.setRoot(LoginPage);
      } else {
        this.loginProvider.validateSession(sessionId).then((isValidSessionId) => {
          if (!isValidSessionId) {
            this.navCtrl.setRoot(LoginPage);
          }else{
            this.statisticsProvider.getStatistics(sessionId).then(results =>{
              this.stats = results;
            }).then(() =>{
              this.updateProgressBar();
              this.updateBarGraph();
            });
          }
          //console.log("valid session for: " + sessionId);
        })
        }
    });
  }
}
